

export default {

    // AUTH

    TOGGLE_GET_STARTED: "TOGGLE_GET_STARTED",
    LOGIN: "LOGIN",
    LOGIN_DONE: "LOGIN_DONE",


    GOOGLE_LOGIN: "GOOGLE_LOGIN",
    FACEBOOK_LOGIN: "FACEBOOK_LOGIN",
    
    SIGNUP: "SIGNUP",
    SIGNUP_DONE: "SIGNUP_DONE",

    EDIT_PROFILE: "EDIT_PROFILE", 

    LOGOUT: "LOGOUT",

    PUT_USER_DATA: "PUT_USER_DATA",
    PUT_USER_TOKEN: "PUT_USER_TOKEN",

    // MAIN
    

    // SETTINGS

}